In [1]:
import numpy as np

In [13]:
##create the folowing using numpy:
array_from_list = np.array([2,4,6,8,10])
print(array_from_list)

#array of 7 zeros
zeros_array = np.zeros(7)
print(zeros_array)

#array of 9 fives
full_array = np.full(9, 5)
print(full_array)

[ 2  4  6  8 10]
[0. 0. 0. 0. 0. 0. 0.]
[5 5 5 5 5 5 5 5 5]


In [22]:
##Given the array arr= np.array([[1,2,3],[2,5,6]])
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [39]:
##Given the array:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print(arr[2,1])
print(arr[1:3,:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
80
[[40 50 60]
 [70 80 90]]


In [40]:
##Given the array:
a = np.array([1,3,5])
b = np.array([2,4,6])
print(a + b)
print(a * b)


[ 3  7 11]
[ 2 12 30]


In [42]:
##for the array
arr = np.array([1,4,9])
print(arr)
print(np.sqrt(arr))
print(np.log(arr))

[1 4 9]
[1. 2. 3.]
[0.         1.38629436 2.19722458]


In [46]:
##use numpy to:
#create an array of numbers from 5 to 50 with a step of 5
arange_array = np.arange(5 ,50, 5)
print(arange_array)
linspace_array = np.linspace(0,1,6)
print(linspace_array)


[ 5 10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8 1. ]


In [55]:
## for the array:
data = np.array([12,15,18,21,24])
print(data)
mean = np.mean(data)
median = np.median(data)
print("mean:", mean)
print("median:", median)
sum_data = np.sum(data)
cumsum_data = np.cumsum(data)
print("sum:",sum_data)
print("cumulative sum:",cumsum_data)

[12 15 18 21 24]
mean: 18.0
median: 18.0
sum: 90
cumulative sum: [12 27 45 66 90]


In [68]:
##Given a 2D array:
Matrix_A = np.array([[1,2],[3,4],[5,6]])
print(Matrix_A)
print(Matrix_A.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
